In the console, type clear and hit Enter or Return. 

This will clear the console output. 

Run the file once while the tasks are longer. 

Copy and paste the terminal results (when task_duration is 3) here.

P1 ADDED Buddy the Dog.
PS C:\Users\jstcl\OneDrive\Documents\streaming-02-multiple-processes> & c:/Users/jstcl/OneDrive/Documents/streaming-01-getting-started/.conda/python.exe c:/Users/jstcl/OneDrive/Documents/streaming-02-multiple-processes/multiple_processes.py


STARTING UP.............................
It's 2023-01-31 at 02:38 PM

This file is running on:    nt Windows 10
The Python version is:      3.10.8
 
The Python interpreter is at: 
 C:\Users\jstcl\OneDrive\Documents\streaming-01-getting-started\.conda\python.exe       


DELETED tabble pets.
CREATED table pets.

P2 getting ready to insert Cooper the Rabbit.
P3 getting ready to insert Emma the Rabbit.
P2 ADDED Cooper the Rabbit.
P1 getting ready to insert Ace the Dog.
P2 getting ready to insert Dufus the Dog.
P2 ADDED Dufus the Dog.
Process Process-3:
Traceback (most recent call last):
  File "C:\Users\jstcl\OneDrive\Documents\streaming-01-getting-started\.conda\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\jstcl\OneDrive\Documents\streaming-01-getting-started\.conda\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\jstcl\OneDrive\Documents\streaming-02-multiple-processes\multiple_processes.py", line 110, in process_three
    insert_pet("P3","Emma", "Rabbit")
  File "c:\Users\jstcl\OneDrive\Documents\streaming-02-multiple-processes\multiple_processes.py", line 95, in insert_pet
    cur.execute(sql)
sqlite3.OperationalError: database is locked
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\jstcl\OneDrive\Documents\streaming-01-getting-started\.conda\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\jstcl\OneDrive\Documents\streaming-01-getting-started\.conda\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\jstcl\OneDrive\Documents\streaming-02-multiple-processes\multiple_processes.py", line 102, in process_one
    insert_pet("P1","Ace", "Dog")
  File "c:\Users\jstcl\OneDrive\Documents\streaming-02-multiple-processes\multiple_processes.py", line 95, in insert_pet
    cur.execute(sql)
sqlite3.OperationalError: database is locked